public class SymbolTable {

    private final HashMap<Integer, Symbol> tabla;

    public SymbolTable() {
    }

    /**
     * El objetivo de esta función es que todas las letras mayúsculas, por ejemplo,
     * sean mapeadas a una misma columna de requerirse.
     * 
     * @param simbolo
     * @return El índice en el que se agregó la entrada.
     */
    public int agregarEntrada(Symbol simbolo) {
    }

    public int existeEntrada(Symbol simbolo) {
    
    }

    public Symbol obtenerEntrada(int indice) {
    }
    
}